defaults: &defaults
  working_directory: /go/src/github.com/ovotech/cluster_name

version: 2.1
jobs:
  goreleaser:
    <<: *defaults

    docker:
      - image: circleci/golang:1.12

    steps:
      - checkout

      - setup_remote_docker:
          docker_layer_caching: true

      - run:
           name: goreleaser
           command: |
             echo $DOCKER_PASS | docker login -u=$DOCKER_USER --password-stdin
             curl -sL https://git.io/goreleaser | VERSION=v0.116.0 bash

workflows:
  version: 2
  release_pipeline:
    jobs:
      - goreleaser:
          filters:
            tags:
              only: /v[0-9]+(\.[0-9]+)*(-.*)*/
            branches:
              ignore: /.*/
      - go_fmt
      - go_vet
      - go_cyclo
      - go_lint
      - go_build
      - go_test