defaults: &defaults
  working_directory: /go/src/github.com/ovotech/cluster_name

version: 2.1
jobs:
  goreleaser:
    <<: *defaults

    docker:
      - image: circleci/golang:1.12

    steps:
      - checkout

      - setup_remote_docker:
          docker_layer_caching: true

      - run:
           name: goreleaser
           command: |
             echo $DOCKER_PASS | docker login -u=$DOCKER_USER --password-stdin
             curl -sL https://git.io/goreleaser | VERSION=v0.116.0 bash

  go_fmt:
    <<: *defaults

    docker:
      - image: eversc/go-pr-checks

    steps:
      - checkout

      - run:
           name: ensure gofmt
           command: |
             test -z $(gofmt -s -l $(find . -iname '*.go' -type f | grep -v /vendor/))
  go_vet:
    <<: *defaults

    docker:
      - image: eversc/go-pr-checks

    steps:
      - checkout

      - run:
           name: go vet
           command: |
             export GO111MODULE=on
             go mod download
             go vet ./...
  go_cyclo:
    <<: *defaults

    docker:
      - image: eversc/go-pr-checks

    steps:
      - checkout

      - run:
           name: go_cyclo
           command: gocyclo -over 6 cmd

  go_lint:
    <<: *defaults

    docker:
      - image: eversc/go-pr-checks

    steps:
      - checkout

      - run:
           name: golint
           command: golint -set_exit_status $(go list ./...)

  go_build:
    <<: *defaults

    docker:
      - image: eversc/go-pr-checks

    steps:
      - checkout

      - run:
           name: go build
           command: |
             export GO111MODULE=on
             go build
  go_test:
    <<: *defaults

    docker:
      - image: eversc/go-pr-checks

    steps:
      - checkout

      - run:
           name: go test
           command: |
             export GO111MODULE=on
             go mod download
             go test ./... -v

workflows:
  version: 2
  release_pipeline:
    jobs:
      - goreleaser:
          filters:
            tags:
              only: /v[0-9]+(\.[0-9]+)*(-.*)*/
            branches:
              ignore: /.*/
      - go_fmt
      - go_vet
      - go_cyclo
      - go_lint
      - go_build
      - go_test